var Factory = require('rosie').Factory;
Factory.define('drugLabel')
  .sequence('set_id', id => `${id}`)
  .sequence('id', id => `${id}`)
  .attr('version', '1')
  .attr('effective_time', '20150101')
  .attr('@epoch', 1420000000.000000)
  .attr('abuse', ['abuse text'])
  .attr('active_ingredient', ['active_ingredient text'])
  .attr('adverse_reactions', ['adverse_reactions text'])
  .attr('animal_pharmacology_and_or_toxicology', ['animal_pharmacology_and_or_toxicology text'])
  .attr('ask_doctor', ['ask_doctor text'])
  .attr('ask_doctor_or_pharmacist', ['ask_doctor_or_pharmacist text'])
  .attr('boxed_warning', ['boxed_warning text'])
  .attr('carcinogenesis_and_mutagenesis_and_impairment_of_fertility', ['carcinogenesis_and_mutagenesis_and_impairment_of_fertility text'])
  .attr('clinical_pharmacology', ['clinical_pharmacology text'])
  .attr('clinical_studies', ['clinical_studies text'])
  .attr('contraindications', ['contraindications text'])
  .attr('controlled_substance', ['controlled_substance text'])
  .attr('dependence', ['dependence text'])
  .attr('description', ['description text'])
  .attr('do_not_use', ['do_not_use text'])
  .attr('dosage_and_administration', ['dosage_and_administration text'])
  .attr('dosage_forms_and_strengths', ['dosage_forms_and_strengths text'])
  .attr('drug_abuse_and_dependence', ['drug_abuse_and_dependence text'])
  .attr('drug_and_or_laboratory_test_interactions', ['drug_and_or_laboratory_test_interactions text'])
  .attr('drug_interactions', ['drug_interactions text'])
  .attr('general_precautions', ['general_precautions text'])
  .attr('geriatric_use', ['geriatric_use text'])
  .attr('how_supplied', ['how_supplied text'])
  .attr('inactive_ingredient', ['inactive_ingredient text'])
  .attr('indications_and_usage', ['indications_and_usage text'])
  .attr('information_for_patients', ['information_for_patients text'])
  .attr('information_for_owners_or_caregivers', ['information_for_owners_or_caregivers text'])
  .attr('instructions_for_use', ['instructions_for_use text'])
  .attr('keep_out_of_reach_of_children', ['keep_out_of_reach_of_children text'])
  .attr('labor_and_delivery', ['labor_and_delivery text'])
  .attr('laboratory_tests', ['laboratory_tests text'])
  .attr('mechanism_of_action', ['mechanism_of_action text'])
  .attr('microbiology', ['microbiology text'])
  .attr('nonclinical_toxicology', ['nonclinical_toxicology text'])
  .attr('nonteratogenic_effects', ['nonteratogenic_effects text'])
  .attr('nursing_mothers', ['nursing_mothers text'])
  .attr('other_safety_information', ['other_safety_information text'])
  .attr('overdosage', ['overdosage text'])
  .attr('package_label_principal_display_panel', ['package_label_principal_display_panel text'])
  .attr('patient_medication_information', ['patient_medication_information text'])
  .attr('pediatric_use', ['pediatric_use text'])
  .attr('pharmacodynamics', ['pharmacodynamics text'])
  .attr('pharmacokinetics', ['pharmacokinetics text'])
  .attr('precautions', ['precautions text'])
  .attr('pregnancy', ['pregnancy text'])
  .attr('pregnancy_or_breast_feeding', ['pregnancy_or_breast_feeding text'])
  .attr('purpose', ['purpose text'])
  .attr('questions', ['questions text'])
  .attr('recent_major_changes', ['recent_major_changes text'])
  .attr('references', ['references text'])
  .attr('safe_handling_warning', ['safe_handling_warning text'])
  .attr('spl_medguide', ['spl_medguide text'])
  .attr('spl_patient_package_insert', ['spl_patient_package_insert text'])
  .attr('spl_product_data_elements', ['spl_product_data_elements text'])
  .attr('spl_unclassified_section', ['spl_unclassified_section text'])
  .attr('stop_use', ['stop_use text'])
  .attr('storage_and_handling', ['storage_and_handling text'])
  .attr('teratogenic_effects', ['teratogenic_effects text'])
  .attr('use_in_specific_populations', ['use_in_specific_populations text'])
  .attr('user_safety_warnings', ['user_safety_warnings text'])
  .attr('warnings', ['warnings text'])
  .attr('warnings_and_precautions', ['warnings_and_precautions text'])
  .attr('when_using', ['when_using text'])
  .attr('openfda', openfda => Factory.build('drugLabelOpenFda', openfda));

Factory.define('drugLabelOpenFda')
  .sequence('spl_id', id => [`${id}`])
  .sequence('spl_set_id', id => [`${id}`])
  .attr('application_number', ['application_number 1'])
  .attr('brand_name', ['brand_name text'])
  .attr('dosage_form', ['dosage_form text'])
  .attr('generic_name', ['generic_name 1, generic_name 2'])
  .attr('manufacturer_name', ['manufacturer_name text'])
  .attr('is_original_packager', [true])
  .attr('product_ndc', ['11111-111'])
  .attr('product_type', ['product_type 1'])
  .attr('route', ['route text'])
  .attr('substance_name', ['substance 1', 'substance 2'])
  .attr('package_ndc', ['11111-111-11'])
  .attr('pharm_class_moa', ['pharm_class_moa text'])
  .attr('pharm_class_cs', ['pharm_class_cs text'])
  .attr('pharm_class_pe', ['pharm_class_pe text'])
  .attr('pharm_class_epc', ['pharm_class_epc text'])
  .attr('upc', ['upc text'])
  .attr('unii', ['unii text'])
  .attr('rxcui', ['rxcui text']);
